version: '3.7'
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:alpine'
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=postgres'
        - 'POSTGRES_DB=postgres'
    volumes:
        - './postgres:/var/lib/postgresql/data'
    networks:
        - 'doublev'

  backend:
    container_name: 'backend'
    build:
        context: ./backend/
        dockerfile: Dockerfile
        target: dev
    restart: 'no'
    ports:
      - '8000:3000'
    environment:
        - 'DB_USER=postgres'
        - 'DB_PASSWORD=postgres'
        - 'DB_NAME=postgres'
        - 'DB_HOST=postgres'
        - 'DB_PORT=5432'
    volumes:
        - './backend:/app'
    networks:
        - 'doublev'

  app:
   container_name: 'frontend'
   build:
      context: ./app/
      dockerfile: Dockerfile
      target: dev
   restart: 'no'
   ports:
      - '8001:3000'
   environment:
      - 'GRAPHQL_URL=http://backend:3000/graphql'
      - 'API_URL=http://backend:3000/'
   volumes:
      - './app:/app'
   networks:
     - 'doublev'

networks:
    doublev:
        driver: 'bridge'